wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1682939550.004106
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.0
      5: 0.14.0
      8:
      - 5
architecture:
  desc: null
  value: RESNET18
dataset:
  desc: null
  value: CIFAR-10
epochs:
  desc: null
  value: 200
learning_rate:
  desc: null
  value: 0.1
